# Generated by Django 5.0.3 on 2024-03-21 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('room', models.IntegerField(choices=[(1, 'Room 1'), (2, 'Room 2'), (3, 'Room 3'), (4, 'Room 4'), (5, 'Room 5')])),
                ('seat', models.IntegerField(choices=[(1, 'Seat 1'), (2, 'Seat 2'), (3, 'Seat 3'), (4, 'Seat 4'), (5, 'Seat 5'), (6, 'Seat 6'), (7, 'Seat 7'), (8, 'Seat 8'), (9, 'Seat 9'), (10, 'Seat 10'), (11, 'Seat 11'), (12, 'Seat 12'), (13, 'Seat 13'), (14, 'Seat 14'), (15, 'Seat 15'), (16, 'Seat 16'), (17, 'Seat 17'), (18, 'Seat 18'), (19, 'Seat 19'), (20, 'Seat 20'), (21, 'Seat 21'), (22, 'Seat 22'), (23, 'Seat 23'), (24, 'Seat 24'), (25, 'Seat 25'), (26, 'Seat 26'), (27, 'Seat 27'), (28, 'Seat 28'), (29, 'Seat 29'), (30, 'Seat 30'), (31, 'Seat 31'), (32, 'Seat 32'), (33, 'Seat 33'), (34, 'Seat 34'), (35, 'Seat 35'), (36, 'Seat 36'), (37, 'Seat 37'), (38, 'Seat 38'), (39, 'Seat 39'), (40, 'Seat 40'), (41, 'Seat 41'), (42, 'Seat 42'), (43, 'Seat 43'), (44, 'Seat 44'), (45, 'Seat 45'), (46, 'Seat 46'), (47, 'Seat 47'), (48, 'Seat 48'), (49, 'Seat 49'), (50, 'Seat 50'), (51, 'Seat 51'), (52, 'Seat 52'), (53, 'Seat 53'), (54, 'Seat 54'), (55, 'Seat 55'), (56, 'Seat 56'), (57, 'Seat 57'), (58, 'Seat 58'), (59, 'Seat 59'), (60, 'Seat 60'), (61, 'Seat 61'), (62, 'Seat 62'), (63, 'Seat 63'), (64, 'Seat 64'), (65, 'Seat 65'), (66, 'Seat 66'), (67, 'Seat 67'), (68, 'Seat 68'), (69, 'Seat 69'), (70, 'Seat 70'), (71, 'Seat 71'), (72, 'Seat 72'), (73, 'Seat 73'), (74, 'Seat 74'), (75, 'Seat 75'), (76, 'Seat 76'), (77, 'Seat 77'), (78, 'Seat 78'), (79, 'Seat 79'), (80, 'Seat 80'), (81, 'Seat 81'), (82, 'Seat 82'), (83, 'Seat 83'), (84, 'Seat 84'), (85, 'Seat 85'), (86, 'Seat 86'), (87, 'Seat 87'), (88, 'Seat 88'), (89, 'Seat 89'), (90, 'Seat 90'), (91, 'Seat 91'), (92, 'Seat 92'), (93, 'Seat 93'), (94, 'Seat 94'), (95, 'Seat 95'), (96, 'Seat 96'), (97, 'Seat 97'), (98, 'Seat 98'), (99, 'Seat 99'), (100, 'Seat 100')])),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('genre', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(choices=[(1, 'Room 1'), (2, 'Room 2'), (3, 'Room 3'), (4, 'Room 4'), (5, 'Room 5')])),
                ('showtime', models.DateTimeField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('title', 'duration', 'year'), name='unique_movie'),
        ),
        migrations.AddField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.movie'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.movie'),
        ),
        migrations.AddField(
            model_name='booking',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.showtime'),
        ),
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.UniqueConstraint(fields=('room', 'showtime'), name='unique_showtime'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('movie', 'room', 'showtime', 'seat'), name='unique_booking'),
        ),
    ]
